### ISSUE TITLE
News prototype(with fake data)

### ISSUE THREAD

**Issue by DaraKlim** [takttusur/takt-public#9]
### **Написать критерии оформления новостей**

Как пользователь, я хочу видеть удобное оформление новостей: краткий текст с описанием, фото с мероприятия, кнопку для быстрого перемещения к источнику, на котором более подробная информация. 
Для того, чтобы легко и быстро воспринимать информацию.

### **Acceptance criteria**

1. Карточки.
   1. На странице три квадратных белых карточки расположенных в ряд. Ниже карточки уже шириной в три маленьких, расположены они друг под другом.
2. Фото.
   1. На первых трёх карточках фото занимает большую их часть, находится по центру, при этом ниже остаётся место для текста. На них фото перелистываются при нажатии кнопок.
   2. Далее фото находятся слева чуть меньше высоты карточки
   3. Фото берутся с новостей группы ТАКТа, первые три карточки самые последние новости новости, далее более старые.
4. Текст.
   1. Текс берётся с новостей группы ТАКТа, первые три карточки самые последние новости, далее более старые. Если есть заголовок, то сначала писать его, потом часть текста с основной информацией.
   2. В углах фото сверху справа находится дата опубликования новости. Оформление текста то же, за исключением цвета, буквы белые.
5.  Кнопки.

    1. На первых трёх карточках по бокам (посередине фото) есть кнопки для перелистывания фото влево (левая кнопка) и вправо (правая кнопка). Квадратные кнопки со стрелками или просто кнопки в виде стрелок.
    2. На всех карточках есть кнопки в правом нижнем углу, для перехода по ссылке на группу вк на эту новость. Синие прямоугольные кнопки со скруглёнными углами.

 
Пример оформления новостей: https://www.figma.com/file/AhAhetnZ1OGl15KGldQAnN/Untitled?type=design&node-id=0-1&mode=design&t=rJMvrZ7d2kcdqBPQ-0

## Technical details

```mermaid

classDiagram
    class INewsService{
        +getArticles(skip, take) Promise~PageModel~ShortArticle~~
        +getArticleById(id) Promise~Article?~
    }
    class NewsServiceFake
    note for NewsServiceFake "Implements the interface using fake data, which is placed in the class"
    NewsServiceFake --|> INewsService
    class ShortArticle{
        +Id : number
        +Title : string
        +TitlePictureUrl : string
        +ModifiedAt : Date
    }
    class Article{
        +Id : number
        +Title : string
        +Text : string
        +CreatedAt : Date
        +ModifiedAt : Date
        +ExternalLink : string?
    }
    class ArticlePageModel{
        +Items : Article[]
        +TotalCount : number
        +Skipped : number
    }
    INewsService ..>ArticlePageModel
    INewsService ..>Article
    INewsService ..>ShortArticle

```

**Comment by andreygolubkow** [comment]
Snapshot of mockup 
![image](https://github.com/takttusur/takt-public/assets/15832039/6956815d-804f-4c68-ba83-dbda59f0cdd3)
